content/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'content'
urlpatterns = [
    path('', views.index, name='index'),
    path('championship/reset/', views.reset_championship_postions, name='reset_championship'),
    path('championship/standings/', views.championship_standings, name='championship_standings'),
    path('championship/standings/<int:see_full>', views.championship_standings, name='championship_standings_full'),
    path('championship/racers/', views.championship_racers, name='championship_racers'),
    path('championship/<slug:the_slug>/', views.championship_index, name='championship_index'),
    path('championship/event/<slug:the_slug>/', views.championship, name='championship'),
    path('team/', views.team, name='team'),
    path('documentation/', views.documentation, name='documentation'),
    path('corporate/', views.corporate, name='corporate'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('join/', views.join, name='join'),
    path('news/', views.news, name='news'),
    path('training/centres', views.training_centres, name='training_centres'),
    ]

website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views as auth_views
#from userauth import views as userauth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('content.urls')),
    path('login/', auth_views.login, {'template_name': 'login.html'}, name='login'),
    path('logout/', auth_views.logout,  {'next_page': '/login'}, name='logout'),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/models.py
from django.db import models

content/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
import pycountry
from datetime import datetime
from django.contrib import messages
from django.urls import reverse
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.gis.geoip2 import GeoIP2
import requests
from . import models
from events.models import *
from pilots.models import *

def get_client_location(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    ip = '87.113.97.255'
    g = GeoIP2()
    country = g.country(ip)
    country = country['country_code']
    response = requests.get('https://restcountries.eu/rest/v2/alpha/' + country)
    geodata = response.json()
    print(geodata)
    return {
        'currencies': geodata['currencies'][0],
        'country': country
    }

def index(request):

	events = EventBasic.objects.filter(completed=False).order_by('-id')[0:4]
	pilots = Pilot.objects.filter(display=True).order_by('last_name')

	championships = Championship.objects.all().order_by('-id')[1]
	champ_events = championships.events.all()

	context = {
		'events' : events,
		'pilots' : pilots,
		'champ_events' : champ_events,
		'championship' : championships,
	}
	template = loader.get_template('content/index.html')
	return HttpResponse(template.render(context, request))


def championship_index(request, the_slug):

	championship = Championship.objects.get(slug=the_slug)
	championship_standings = ChampionshipPosition.objects.filter(championship=championship).order_by('championship_position')

	context = {
		'championship' : championship,
		'championship_standings' : championship_standings,
	}

	template = loader.get_template('content/championship-index.html')
	return HttpResponse(template.render(context, request))

def championship(request, the_slug):
	event = EventBasic.objects.get(slug=the_slug)
	competitors = event.competitors.all().order_by('final_position')

	context = {
		'event' : event,
		'competitors' : competitors,
	}

	if event.completed == True:
		template = loader.get_template('content/championship.html')
	else:
		template = loader.get_template('content/championship-future.html')

	return HttpResponse(template.render(context, request))

def championship_racers(request):
	pilots = Pilot.objects.all().order_by('last_name')
	championships = Championship.objects.all().order_by('-id')[1]
	context = {
		'pilots' : pilots,
		'championship' : championships,
	}

	template = loader.get_template('content/drivers.html')
	return HttpResponse(template.render(context, request))

def championship_standings(request, see_full=None):
	pilots = Pilot.objects.all().order_by('championship_position')
	events = EventBasic.objects.filter(completed=True).order_by('id')

	context = {
		'pilots' : pilots,
		'events' : events,
	}
	
	if see_full == True:
		template = loader.get_template('content/drivers-full-results.html')
	else:
		template = loader.get_template('content/drivers-championship.html')

	return HttpResponse(template.render(context, request))

def reset_championship_postions(request):
	for pilot in Pilot.objects.all():
		pos = 1
		if not pilot.total_points():
			pos = Pilot.objects.all().count()
		else:
			for p in Pilot.objects.all():
				if not p == pilot and p.total_points():
					if p.total_points() > pilot.total_points():
						pos=pos+1

			pilot.championship_position = pos
			pilot.save()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

def team(request):

	context = {

	}
	
	template = loader.get_template('content/team.html')
	return HttpResponse(template.render(context, request))

def documentation(request):

	docs = Documentation.objects.filter(document_active=True)

	context = {

		'docs' : docs,

	}

	template = loader.get_template('content/documentation.html')
	return HttpResponse(template.render(context, request))

def corporate(request):

	context = {

	}
	
	template = loader.get_template('content/corporate.html')
	return HttpResponse(template.render(context, request))

def about(request):

	boats = Boat.objects.filter(boat_number__gt=0)

	context = {

		'boats': boats,

	}
	
	template = loader.get_template('content/about.html')
	return HttpResponse(template.render(context, request))

def contact(request):

	if request.method == "POST":
		name = request.POST.get("name")
		email = request.POST.get("email")
		subject = request.POST.get("company")
		message = request.POST.get("request")



	context = {


	}
	
	template = loader.get_template('content/contact.html')
	return HttpResponse(template.render(context, request))


def join(request):
	paypal_dict = {
        "business": "receiver_email@example.com",
        "amount": "10000000.00",
        "item_name": "name of the item",
        "invoice": "unique-invoice-id",
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn'))
    }

    # Create the instance.
	form = PayPalPaymentsForm(initial=paypal_dict)

	context = {
		'form' : form,
	}
	
	template = loader.get_template('content/join_us.html')
	return HttpResponse(template.render(context, request))

def training_centres(request):

	context = {

	}

	template = loader.get_template('content/training_centres.html')
	return HttpResponse(template.render(context, request))

def news(request):

	context = {

	}

	template = loader.get_template('content/news.html')
	return HttpResponse(template.render(context, request))

content/templates/content/about.html
{% extends "base_site.html" %}
{% load humanize %}
{% load template_tags %}
{% block title %} About {% endblock title %}

{% block content %}
<div class="container-fluid page-title">
	<div class="row">
		<div class="col-sm-12 col-lg-10 col-lg-offset-1">
			<div class="row">
				<h4>
					ABOUT US</span>
				</h4>
			</div>
		</div>
	</div>
</div> 
<div class="container-fluid event-gallery">
	<div class="row">
		<div class="row">
				<div class="col-xs-12 home-vip-title text-center" style="color: rgb(255,223,0) !important;text-transform: uppercase;"><span>The Concept</span></div>
			</div>
		<div class="col-sm-12 col-lg-10 col-lg-offset-1">

			<div class="row">
				<div class="media-list">
					{% for event in events %}
					<div class="media-item">
							<a href="{% url 'content:championship' event.slug %}" class="gallery-box">
								<div class="media-content">
									<div class="media-cover" style="background-image:url({{ event.event_cover.url }});">
										<div>&nbsp;</div>
									</div>
									<div class="media-info">
										<div><small style="text-transform: uppercase;">{% if event.event_date %}{{ event.event_date|date:"F Y"}}{% else %}{{ event.event_proposed_date }}{% endif %}</small></div>
										<div><strong style="text-transform: uppercase;">{{ event.event_title }}</strong></div>
										<div style="text-transform: uppercase;">{% if event.event_date %}{% if event.event_past == true %}See the Results{% else %}Find Out More{% endif %}{% else %}Register Your Interest{% endif %}</div>
									</div>
								</div>
							</a>
					</div>
					{% endfor %}							
			</div>
		</div>
	</div>
</div>
</div>

<div id="home-teams" class="container-fluid">
	<div class="row">
		<div class="col-xs-12 home-vip-title text-center" style="color: rgb(255,223,0) !important;"><span>OUR FLEET</span></div>
	</div>
	<div class="row">
		
		<div class="col-sm-12 col-lg-10 col-lg-offset-1">
				    <div class="home-teamslider-container">
				    	{% for boat in boats %}
					    <div class="home-driverslider-item">
				                <div class="driver-item">
				                	<div class="driver-photo" style="background-image:url('{{ boat.boat_image.url }}');min-height: 30em;">
				                		
				                	</div>
				                    <div class="driver-name">
				                        <h3>
				                        	Boat Number: {{ boat.boat_number }}			                        	<span class="pull-right flag-icon flag-icon-gb"></span>&nbsp;<span class="pull-right flag-icon flag-icon-hk"></span>
				                        </h3>
				                        <div class="driver-info pull-left">
				                            <div class="driver-info-text">MANUFACTURER: <span>Shakespeare Boats</span></div>
				                            <div class="driver-info-text">YEAR OF MANUFACTURE: <span>2017</span></div>
				                            <div class="driver-info-text">STEERING: <span>Hydraullic</span></div>
				                            <div class="driver-info-text">HULL LENGTH: <span>4,285 mm</span></div>
				                            <div class="driver-info-text">BEAM: <span>1,505 mm</span></div>
				                            <div class="driver-info-text">HULL WEIGHT: <span>110 kg</span></div>
				                            <div class="driver-info-text">ENGINE: <span>TOHATSU 50HP 2 Stroke MD50D2</span></div>
				                            <div class="driver-info-text">RACE WEIGHT: <span>235 kg</span></div>
				                        </div>
				                        <div class="driver-icon pull-left">
				                        	<i class="fa fa-ship" style=""></i>
				                        </div>
				                        <div class="driver-championship pull-left">
				                        	<!--<div class="driver-championship-text">RACES: <span>{{ boat.number_of_races }}</span></div>-->
				                        	<div class="driver-championship-text">RACED IN: <span>{% for event in boat.location %}<span class="flag-icon {{ event.get_flag }}"></span>{% if not forloop.last %}&nbsp;{% endif %}{% endfor %}</span></div>
				                            <div class="driver-championship-text">PILOTS: <span>{% for pilot in boat.boat_pilots %}{{ pilot.entrant.first_name }} {{ pilot.entrant.last_name }}{% if not forloop.last %}, {% endif %}{% endfor %}</span></div>		                            
				                        </div>
				                    </div>
				                </div>
						</div>
						{% endfor %}
							
					</div>
				</div>
			</div>
	</div>
	<div id="home-video" class="container-fluid" style="background-image:url('/static/images/promo-video.jpg')">
	<div class="row">
		<div class="col-sm-12 col-lg-10 col-lg-offset-1">
			<div class="col-xs-12 home-vip-title">
				<span>
					<a id="video-box" href="javascript:void(0);" data-filename="2019_F1H2O_Season_Review" data-videotitle=" - Season End Highlights" data-slug="320--season-end-highlights" data-season="2019">
						<i class="fa fa-youtube-play"></i> 					<div id="video-player-container" style="display:none"><div id="video-player"></div></div>
					</a>
				</span>
			</div>
		</div>
	</div>
	</div>
	<div class="container-fluid event-gallery">
	<div class="row">
		<div class="row">
				<div class="col-xs-12 home-vip-title text-center" style="color: rgb(255,223,0) !important;text-transform: uppercase;"><span>CHAMPIONSHIP FORMAT</span></div>
			</div>
		<div class="col-sm-12 col-lg-10 col-lg-offset-1">

			<div class="row">
				<div class="media-list">
					{% for event in champ_events %}
					<div class="media-item-training">
							<a href="{% url 'content:championship' event.slug %}" class="gallery-box">
								<div class="media-content">
									<div class="media-cover" style="background-image:url({{ event.event_cover.url }});">
										<div>&nbsp;</div>
									</div>
									<div class="media-info">
										<div><small style="text-transform: uppercase;">{% if event.event_date %}{{ event.event_date|date:"F Y"}}{% else %}{{ event.event_proposed_date }}{% endif %}</small></div>
										<div><strong style="text-transform: uppercase;">{{ event.event_title }}</strong></div>
										<div style="text-transform: uppercase;">{% if event.event_date %}{% if event.event_past == true %}See the Results{% else %}Find Out More{% endif %}{% else %}Register Your Interest{% endif %}</div>
									</div>
								</div>
							</a>
					</div>
					{% endfor %}							
			</div>
		</div>
	</div>
</div>
</div>
<div id="home-teams" class="container-fluid">
	<div class="row">
		<div class="col-xs-12 text-center home-vip-title" style="color: rgb(255,223,0) !important;"><span>TRAINING</span></div>
	</div>
	<div class="row">
		
		<div class="col-sm-12 col-lg-10 col-lg-offset-1">
			<div class="media-list">
					<div class="media-item-training">
							<a href="#" class="gallery-box">
								<div class="media-content">
									<div class="media-cover" style="background-image:url(static/images/training-1.jpg);">
										<div>&nbsp;</div>
									</div>
									<div class="media-info">
										<div><strong>EXMOUTH, UK</strong><span class="pull-right flag-icon flag-icon-gb"></span></div>
										<div><small>LEVELS: Novice - Advanced</small></div>
										<div><small>CHIEF INSTRUCTOR: Guy Child</small></div>
									</div>
								</div>
							</a>
						</div>
						<div class="media-item-training">
							<a href="#" class="gallery-box">
								<div class="media-content">
									<div class="media-cover" style="background-image:url(static/images/training-2.jpg);">
										<div>&nbsp;</div>
									</div>
									<div class="media-info">
										<div><strong>CHANGI, SG</strong><span class="pull-right flag-icon flag-icon-sg"></span></div>
										<div><small>LEVELS: Novice</small></div>
										<div><small>CHIEF INSTRUCTOR: Campbell Jenkins</small></div>
									</div>
								</div>
							</a>
						</div>
						<div class="media-item-training">
							<a href="#" class="gallery-box">
								<div class="media-content">
									<div class="media-cover" style="background-image:url(static/images/training-3.jpg);">
										<div>&nbsp;</div>
									</div>
									<div class="media-info">
										<div><strong>HONG KONG</strong><span class="pull-right flag-icon flag-icon-hk"></span></div>
										<div><small>LEVELS: Novice - Intermediate</small></div>
										<div><small>CHIEF INSTRUCTOR: John Lindsay</small></div>
									</div>
								</div>
							</a>
						</div>
			</div>
		</div>
	</div>
</div>
<div class="container-fluid event-gallery">
	<div class="row">
		<div class="row">
				<div class="col-xs-12 home-vip-title text-center" style="color: rgb(255,223,0) !important;text-transform: uppercase;"><span>UNION INTERNATIONALE MONONAUTIQUE</span></div>
			</div>
		<div class="col-sm-12 col-lg-10 col-lg-offset-1">

			<div class="row">
				<div class="media-list">
					{% for event in champ_events %}
					<div class="media-item-training">
							<a href="{% url 'content:championship' event.slug %}" class="gallery-box">
								<div class="media-content">
									<div class="media-cover" style="background-image:url({{ event.event_cover.url }});">
										<div>&nbsp;</div>
									</div>
									<div class="media-info">
										<div><small style="text-transform: uppercase;">{% if event.event_date %}{{ event.event_date|date:"F Y"}}{% else %}{{ event.event_proposed_date }}{% endif %}</small></div>
										<div><strong style="text-transform: uppercase;">{{ event.event_title }}</strong></div>
										<div style="text-transform: uppercase;">{% if event.event_date %}{% if event.event_past == true %}See the Results{% else %}Find Out More{% endif %}{% else %}Register Your Interest{% endif %}</div>
									</div>
								</div>
							</a>
					</div>
					{% endfor %}							
			</div>
		</div>
	</div>
</div>
</div>
{% endblock content %}

content/templates/content/championship-index.html
{% extends "base_site.html" %}
{% load humanize %}
{% load template_tags %}
{% block title %} {{ championship.name }} {% endblock title %}
{% block stylesheets %}
	{{ block.super }}
  <style>
    .insidef1h2o-item {
	display: flex;
	flex-wrap:wrap;
	background-color:white;
}

.insidef1h2o-item-photo {
	display: flex;
	flex-wrap:wrap;
	background:center center;
	background-size:cover;
	min-height:120px;
}

.insidef1h2o-item>.insidef1h2o-title {
	padding-left: 15px;
	padding-right: 15px;
	padding-top:100px;
	padding-bottom:80px;
	width: 40%;
	font-size:3.0em;
	font-weight:700;
	text-transform:uppercase;
	text-align:right;
	line-height:1.0em;
}

.insidef1h2o-item>.insidef1h2o-text {
	padding:15px 100px 60px;
	padding-top:110px;
	width: 60%;
	font-size:0.8em;
}

.insidef1h2o-item>.insidef1h2o-title2 {
	padding:100px 100px 50px 100px;
	font-size:1.4em;
	font-weight:700;
	text-transform:uppercase;
}

.insidef1h2o-item>.insidef1h2o-text2 {
	font-size:0.8em;
	padding:80px 80px 80px 80px;
}

.insidef1h2o-title-white {
	padding:150px 150px 50px 150px;
	font-size:1.6em;
	font-weight:700;
	text-transform:uppercase;
	color:white;
	text-align:center;
	width:100%;
}

.insidef1h2o-text-white {
	padding:0px 150px 150px 150px;
	font-size:1.1em;
	font-style:italic;
	color:white;
	text-align:center;
}
p a {
	text-decoration:underline;
}

@media (max-width: 767px) {
	.insidef1h2o-item>.insidef1h2o-title {
		width: 100%;
		padding:15px;
	}
	
	.insidef1h2o-item>.insidef1h2o-text {
		width: 100%;
		padding:15px;
	}

	.insidef1h2o-item>.insidef1h2o-title2 {
		padding:15px;
	}
	
	.insidef1h2o-item>.insidef1h2o-text2 {
		padding:15px;
	}
	
	.insidef1h2o-title-white {
		padding:15px;
	}
	
	.insidef1h2o-text-white {
		padding:15px;
	}
}
</style>
{% endblock stylesheets %}
{% block content %}

<div class="container-fluid event-gallery">
	<div class="row">
		<div class="row">
				<div class="col-xs-12 home-vip-title text-center" style="color: rgb(255,223,0) !important;text-transform: uppercase;"><span>{{ championship.name }} Events</span></div>
			</div>
		<div class="col-sm-12 col-lg-10 col-lg-offset-1">

			<div class="row">
				<div class="media-list">
					{% for event in championship.events.all %}
					<div class="media-item">
							<a href="{% url 'content:championship' event.slug %}" class="gallery-box">
								<div class="media-content">
									<div class="media-cover" style="background-image:url({{ event.event_cover.url }});">
										<div>&nbsp;</div>
									</div>
									<div class="media-info">
										<div><small style="text-transform: uppercase;">{% if event.event_date %}{{ event.event_date|date:"F Y"}}{% else %}{{ event.event_proposed_date }}{% endif %}</small></div>
										<div><strong style="text-transform: uppercase;">{{ event.event_title }}</strong></div>
										<div style="text-transform: uppercase;">{% if event.event_date %}{% if event.event_past == true %}See the Results{% else %}Find Out More{% endif %}{% else %}Register Your Interest{% endif %}</div>
									</div>
								</div>
							</a>
					</div>
					{% endfor %}							
			</div>
		</div>
	</div>
</div>
</div>
{% if championship_standings.all %}
<div id="home-teams" class="container-fluid">
	<div class="row">
		<div class="col-xs-12 home-vip-title text-center" style="color: rgb(255,223,0) !important; text-transform: uppercase;"><span>{{ championship.name }} RACERS</span></div>
	</div>
	<div class="row">
		
		<div class="col-sm-12 col-lg-10 col-lg-offset-1">
				    <div class="home-teamslider-container">
				    	{% for pilot in championship_standings %}
					    <div class="home-driverslider-item">
				                <div class="driver-item">
				                	<div class="driver-photo" style="background-image:url('{% if pilot.pilot.display == True %}{{ pilot.pilot.profile_image.url }}{% else %}/static/images/avatar.jpg{% endif %}');min-height: 30em;">
				                		
				                	</div>
				                    <div class="driver-name">
				                        <h3>
				                        	{{ pilot.pilot.first_name }} {{ pilot.pilot.last_name}}			                        	<span class="pull-right flag-icon {{ pilot.pilot.get_flag }}"></span>
				                        </h3>
				                        <div class="driver-info pull-left">
				                            <div class="driver-info-text">COUNTRY: <span>{{ pilot.pilot.nationality.name }}</span></div>
				                            {% if pilot.pilot.dob %}
				                            <div class="driver-info-text">DATE OF BIRTH: <span>{{ pilot.pilot.dob|date:"d/m/Y"}}</span></div>
				                            {% endif %}
				                            {% if pilot.pilot.height %}
				                            <div class="driver-info-text">HEIGHT: <span>{{pilot.pilot.height}} CM</span></div>
				                            {% endif %}
				                            {% if pilot.pilot.weight %}
				                            <div class="driver-info-text">WEIGHT: <span>{{ pilot.pilot.weight }} KG</span></div>
				                            {% endif %}
				                            <div class="driver-info-text">BIO: <span style="text-align: justify;">{{ pilot.pilot.bio|truncatechars:500}}</span></div>
				                            <div class="driver-info-text">LINKS: <span><a href="{{ pilot.pilot.facebook }}" target="_blank"><i class="fa fa-facebook"></i></a>&nbsp;&nbsp;&nbsp;<a href="{{ pilot.pilot.instagram }}" target="_blank"><i class="fa fa-instagram"></i></a>&nbsp;&nbsp;&nbsp;<a href="{{ pilot.pilot.twitter }}" target="_blank"><i class="fa fa-twitter"></i></a>&nbsp;&nbsp;&nbsp;<a href="{{ pilot.pilot.youtube }}" target="_blank"><i class="fa fa-youtube"></i></a>&nbsp;&nbsp;&nbsp;<a href="{{ pilot.pilot.website }}" target="_blank"><i class="fa fa-globe"></i></a></span></div>
				                        </div>
				                        <div class="driver-icon pull-left">
				                        	<i class="fa fa-trophy" style="{% if pilot.championship_position == 1 %}color: #D4AF37;{% endif %}{% if pilot.championship_position == 2 %}color: #C0C0C0;{% endif %}{% if pilot.championship_position == 3 %}color: #cd7f32;{% endif %}"></i>
				                        </div>
				                        <div class="driver-championship pull-left">
				                        	<div class="driver-championship-text">POSITION: <span>{{ pilot.championship_position|ordinal }}</span></div>
				                        	<div class="driver-championship-text">POINTS: <span>{% get_championship_points championship.id pilot.pilot.id %}</span></div>
				                            <div class="driver-championship-text">CHAMPIONSHIPS: <span>{% get_championship_entered championship.id pilot.pilot.id %}</span></div>
				                            <div class="driver-championship-text">BEST RESULT: <span>{% get_championship_best championship.id pilot.pilot.id %}</span></div>
				                            <div class="driver-championship-text">PODIUMS: <span>{% get_championship_podiums championship.id pilot.pilot.id %}</span></div>
				                            
				                        </div>
				                    </div>
				                </div>
						</div>
						{% endfor %}
							
					</div>
				</div>
			</div>
	</div>
	{% endif %}
	{% if championship_standings.all %}
	<div class="container-fluid event-gallery">
	<div class="row">
		<div class="row">
				<div class="col-xs-12 home-vip-title text-center" style="color: rgb(255,223,0) !important;text-transform: uppercase;"><span>{{ championship.name }} standings</span></div>
			</div>
		<div class="col-sm-12 col-lg-10 col-lg-offset-1">

			<div class="row">
				<div class="insidef1h2o-item">
				<table class="table table-condensed table-standings">
										<thead>
											<tr>
												<th class="std-pos" rowspan="2">POS</th>
												<th class="std-flag" rowspan="2">DRIVER</th>
												<th class="std-flag" rowspan="2">NAT</th>
												<th class="std-flag" colspan="{{ championship.events.count|add:'1'}}">2018/2019 Asia Powerboat Championship</th>
												
											</tr>
											<tr>
												{% for event in championship.events.all %}
													<th class="std-flag"><span class="flag-icon {{event.get_flag}}"></span></th>
												{% endfor %}
												<th class="std-laps">TOTAL</th>
											</tr>
										</thead>
										<tbody>
											{% for comp in championship_standings %}
											{% if comp.championship_position %}
											<tr>
												<td class="std-pos"><span>{{ comp.championship_position }}</span></td>
												<td class="std-flag" style="text-transform: uppercase;">{{ comp.pilot.first_name }} {{ comp.pilot.last_name }}</span></td>
												<td class="std-flag"><span class="flag-icon {{comp.pilot.get_flag}}"></span></td>
												{% for event in championship.events.all %}
													<td class="std-laps">{% get_driver_event event.id comp.pilot.id %}</td>
												{% endfor %}
												<td class="std-points"><span>{% get_championship_points championship.id comp.pilot.id %}</span></td>
											</tr>
											{% endif %}
											{% endfor %}
											
										</tbody>
									</table>
				</div>
				
		</div>
	</div>
</div>
</div>
{% endif %}
{% endblock content %}

content/templates/content/documentation.html
{% extends "base_site.html" %}
{% load humanize %}
{% load template_tags %}
{% block title %} Documentation {% endblock title %}

{% block content %}

<div class="container-fluid page-title">
	<div class="row">
		<div class="col-sm-12 col-lg-10 col-lg-offset-1">
			<div class="row">
				<h4>
					DOCUMENTATION</span>
				</h4>
			</div>
		</div>
	</div>
</div> 
<div id="home-teams" class="container-fluid">
		<div class="row">
		
		<div class="col-sm-12 col-lg-10 col-lg-offset-1">
			<div class="media-list">
				{% for doc in docs %}
					<div class="media-item-training">
							<a href="{{ doc.document_link }}" class="gallery-box" target="_blank">
								<div class="media-content">
									<div class="media-cover" style="background-image:url(https://apachampionship.com/apa/wp-content/uploads/2019/11/APA-Logo-600.png);">
										<div>&nbsp;</div>
									</div>
									<div class="media-info">
										<div style="text-transform: uppercase;"><strong>{{ doc.document_name }}</strong></div>
										<div><small>VERSION: {{ doc.document_version }}</small></div>
										<div><small>PUBLISHED: {{ doc.document_published|date:"M Y" }}</small></div>
									</div>
								</div>
							</a>
						</div>
					{% endfor %}
			</div>
		</div>
	</div>
</div>
		
{% endblock content %}